Repository myungjuice/myungjoo-dev, pull requests merged in 2025-04, with the labels that each got.

#1 feat: About 페이지 작업
  package.json
  pnpm-lock.yaml
  public/images/profile.jpeg
  src/app/(main)/_components/snake-game/index.tsx
  src/app/(main)/_components/snake-game/snake-canvas.tsx
  src/app/(main)/_components/snake-game/start-overlay.tsx
  src/app/(main)/page.tsx
  src/app/about/_components/divider.tsx
  src/app/about/_components/main-content.tsx
  src/app/about/_components/menu-item.tsx
  src/app/about/_components/side-content-item.tsx
  src/app/about/_components/side-content.tsx
  src/app/about/_components/sidebar-content.tsx
  src/app/about/page.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/components/layout/footer.tsx
  src/components/layout/header/index.tsx
  src/components/layout/index.tsx
  src/components/shared/code-highlight.tsx
  src/components/shared/fade-in-up.tsx
  src/components/shared/section-title.tsx
  src/components/sidebar/index.tsx
  src/components/sidebar/sidebar-container.tsx
  src/components/sidebar/sidebar-tab.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/constants/about/index.ts
  src/constants/about/main-content.ts
  src/constants/folder-colors.ts
  src/hooks/use-canvas-snake-game.ts
  src/lib/i18n/about.ts
  src/lib/i18n/client.ts
  src/store/__tests__/use-about-page-store.test.ts
  src/store/index.ts
  src/store/use-about-page-store.ts
  src/types/about.ts
  src/types/code-highlight.ts
Labels: enhancement

#6 refactor: console warning 제거 (ESM import, Image fill)
  src/app/career/_components/main-content.tsx
  src/constants/career.ts
Labels: refactor

#8 feat: SideContent 랜덤 코드 기능 추가 및 중복 제거, 날짜 정렬 기능 추가
  src/components/shared/side-content/index.tsx
Labels: enhancement

#9 feat: 메인 페이지 CodeHighlight 내용 수정
  src/app/(main)/page.tsx
  src/lib/i18n/main.json
Labels: enhancement

#10 feat: 메인 페이지에 Code Toggle 기능 추가 및 CodeHighlight 내용 수정
  package.json
  pnpm-lock.yaml
  src/app/(main)/_components/Hello.tsx
  src/app/(main)/_components/snake-game/index.tsx
  src/app/(main)/_components/snake-game/snake-canvas.tsx
  src/app/(main)/page.tsx
  src/components/ui/toggle.tsx
  src/hooks/use-canvas-snake-game.ts
  src/lib/i18n/main.json
Labels: enhancement

#11 docs: README.md 수정
  .github/PULL_REQUEST_TEMPLATE.md
  public/images/readme_main.gif
  src/app/(main)/page.tsx
Labels: documentation

#15 fix: getMappedKey 적용하여 한글 필터 탭 버그 수정
  src/app/career/page.tsx
  src/app/projects/page.tsx
  src/components/shared/section-title/section-title-item.tsx
  src/lib/__tests__/utils.test.ts
  src/lib/utils.ts
Labels: bug

#16 feat: 선택된 필터/기술 항목 정렬 기능 추가
  src/lib/__tests__/utils.test.ts
  src/lib/utils.ts
  src/store/use-career-page-store.ts
  src/store/use-projects-page-store.ts
Labels: enhancement

#17 chore: patch release v1.0.2
  package.json
Labels: release, patch

#18 feat: 언어 쿠키 처리 기능 추가
  .husky/pre-commit
  src/app/(main)/page.tsx
  src/components/shared/language-toggle.tsx
  src/lib/__tests__/get-lang-from-cookie.test.ts
  src/lib/get-lang-from-cookie.ts
Labels: enhancement

#19 feat: hello API 연동
  package.json
  pnpm-lock.yaml
  src/app/(main)/_components/code-view.tsx
  src/app/(main)/_components/main.tsx
  src/app/(main)/page.tsx
  src/app/api/hello/route.ts
  src/app/error.tsx
  src/components/shared/error-content.tsx
  src/components/ui/spinner.tsx
  src/lib/api/hello.ts
  src/lib/api/index.ts
  src/providers/index.tsx
  src/providers/query-client-provider.tsx
  src/types/api.ts
  src/types/hello.ts
Labels: enhancement

#20 feat: 메인 페이지 스켈레톤 UI 구현
  .eslintrc.json
  src/app/(main)/_components/code-view.tsx
  src/app/(main)/_components/main.tsx
  src/app/(main)/page.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/spinner.tsx
  src/types/language.ts
Labels: enhancement

#21 fix: 메인 페이지에서 최초 렌더시 API 중복 호출하는 버그 수정
  src/app/(main)/_components/main.tsx
Labels: bug

#23 chore: github 정보 변경
  README.md
  src/components/shared/side-content/index.tsx
  src/lib/i18n/projects.ts
Labels: style
